---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aws-cost-export
spec:
  schedule: "0 5 1 * *" # Change me to your schedule
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: aws-cost-export
              image: ghcr.io/andresb39/aws_go_report/aws_cost_export:0.0.1
              imagePullPolicy: Always
              env:
                - name: To
                  valueFrom:
                    secretKeyRef:
                      name: cost-export
                      key: TO
                - name: From
                  valueFrom:
                    secretKeyRef:
                      name: cost-export
                      key: FROM
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: cost-export
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: cost-export
                      key: AWS_SECRET_ACCESS_KEY
                - name: Region
                  valueFrom:
                    secretKeyRef:
                      name: cost-export
                      key: AWS_DEFAULT_REGION

          restartPolicy: OnFailure